### ISSUE TITLE
Low Adv. accuracy of "Basic Training with Robust Dataset"

### ISSUE THREAD

**Issue by kiranchari** [ndb796/Pytorch-Adversarial-Training-CIFAR#1]
Hi, 

I downloaded the model weights for "Basic Training with Robust Dataset" from this repo and tested my own L-inf PGD attack (epsilon 8/255, without random init). The adv. accuracy is just 0.1% under my attack, which is different from the numbers you have observed (~37%). Any ideas why this maybe the case?

Thank you.

**Comment by kiranchari** [comment]
I think the number you have reported on the README page are for l2-pgd not linf-pgd. I am able to get similar adv. accuracy when I do an l2-pgd (eps: 0.25) on the model of around 38%.

**Comment by ndb796** [comment]
Hi, @kiranchari.

Thank you for your comments!
You're right.

<b>PGD Training [Madry'18]</b> and <b>Interpolated Adversarial Training (IAT) [Lamb'19]</b> methods are trained on _L-infinity_ adversarial examples.
Therefore, these methods are evaluated on the same _L-infinity_ attacks.

But, <b>robust Dataset and non-robust Dataset [Ilyas'19]</b> are conducted utilizing _L2_ adversarial examples.
Thus, this method is evaluated on _L2_ attacks.

The result "37.96%" of the method [Ilyas'19] is for _L2_ attacks. 
Sorry for typos in my README file.

**Comment by kiranchari** [comment]
Thanks @ndb796
